Repository 107-systems/.github, pull requests merged in 2021-09, with the labels that each got.

#35 Pull in improvements to the label sync workflow template
  .github/workflows/manage-labels.yml
  .github/workflows/sync-labels.yml
  universal-repository-labels.json
  workflow-templates/assets/sync-labels/universal.yml
  workflow-templates/manage-labels.yml
  workflow-templates/sync-labels.properties.json
  workflow-templates/sync-labels.svg
  workflow-templates/sync-labels.yml
Labels: type: enhancement

#36 Remove sketch CI status.
  README.md
Labels: topic: documentation, type: bug

#37 Add 107-Arduino-Sensor CI library status.
  README.md
Labels: type: enhancement, topic: documentation

#38 Add 107-Arduino-BoostUnits to CI library status.
  README.md
Labels: type: enhancement, topic: documentation

#39 Add @per1234 to sponsor list
  README.md
Labels: type: enhancement, topic: documentation

#40 Add @aentinger to sponsor list.
  README.md
Labels: type: enhancement, topic: documentation

#41 Create a profile text.
  profile/README.md
Labels: type: enhancement, topic: documentation
