Repository 107-systems/.github, pull requests merged in 2021-08, with the labels that each got.

#30 Link logo to 107-Arduino-DroneCore
  README.md
Labels: topic: documentation

#32 Enforce usage of issue template.
  ISSUE_TEMPLATE/config.yml
Labels: type: enhancement, topic: documentation

#33 Fix: Move folder ISSUE_TEMPLATE inside the .github folder
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: enhancement, topic: documentation

#34 Add front matter to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: bug
